int pu = 8;
int l1 = 7;
int l2 = 6;
int l3 = 5;
int l4 = 4;
int l5 = 3;
int l6 = 2;
int l7 = 1;
int l8 = 0;
int x = 1;
int pu_val = 0;
void setup () {
pinMode (pu,INPUT);
pinMode (l1,OUTPUT);
pinMode (l2,OUTPUT);
pinMode (l3,OUTPUT);
pinMode (l4,OUTPUT);
pinMode (l5,OUTPUT);
pinMode (l6,OUTPUT);
pinMode (l7,OUTPUT);
pinMode (l8,OUTPUT);
void pattern1();
void pattern2();
void pattern3();
void pattern4();
void pattern5();
}
void loop () {
if (digitalRead(pu)==1){
pu_val = 1;
}
if (pu_val == 1){
  if (x==1){
pattern1();
  }
  else if (x==2){
  pattern2();
  }
  else if (x==3){
  pattern3();
  }
  else if (x==4){
  pattern4();
  }
  else if (x==5){
  pattern5();
  }
}
}
void pattern1(){
digitalWrite (l1,1);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,1);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,1);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,1);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,1);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,1);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,1);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
x=2;
pu_val = 0;
}
void pattern2(){
digitalWrite (l1,1);
digitalWrite (l2,0);
digitalWrite (l3,1);
digitalWrite (l4,0);
digitalWrite (l5,1);
digitalWrite (l6,0);
digitalWrite (l7,1);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,1);
digitalWrite (l3,0);
digitalWrite (l4,1);
digitalWrite (l5,0);
digitalWrite (l6,1);
digitalWrite (l7,0);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,1);
digitalWrite (l2,0);
digitalWrite (l3,1);
digitalWrite (l4,0);
digitalWrite (l5,1);
digitalWrite (l6,0);
digitalWrite (l7,1);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,1);
digitalWrite (l3,0);
digitalWrite (l4,1);
digitalWrite (l5,0);
digitalWrite (l6,1);
digitalWrite (l7,0);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
x=3;
pu_val = 0;
}
void pattern3(){
digitalWrite (l1,1);
digitalWrite (l2,1);
digitalWrite (l3,1);
digitalWrite (l4,1);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,1);
digitalWrite (l6,1);
digitalWrite (l7,1);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,1);
digitalWrite (l2,1);
digitalWrite (l3,1);
digitalWrite (l4,1);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,1);
digitalWrite (l6,1);
digitalWrite (l7,1);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
x=4;
pu_val = 0;
}
void pattern4(){
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,1);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,1);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,1);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,1);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,1);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,1);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,1);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
x=5;
pu_val = 0;
}
void pattern5(){
digitalWrite (l1,1);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,1);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,1);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,1);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,1);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,1);
digitalWrite (l5,1);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,1);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,1);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,1);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,1);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,1);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
delay (250);
digitalWrite (l1,1);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,1);
delay (250);
digitalWrite (l1,0);
digitalWrite (l2,0);
digitalWrite (l3,0);
digitalWrite (l4,0);
digitalWrite (l5,0);
digitalWrite (l6,0);
digitalWrite (l7,0);
digitalWrite (l8,0);
x=1;
pu_val = 0;
}
